### ISSUE TITLE
[FR] Pass sample as argument to SampleParser functions to support parallelization

### ISSUE THREAD

**Issue by jneeven** [voxel51/fiftyone#1045]
### Proposal Summary
This is as much a question as it is a proposal, but since I run into this fact when trying to parallize the parsing of samples (a feature I'm willing to contribute), I figured this might be an appropriate place for it anyway :)

When parsing samples into a dataset, `sample_parser.with_sample(sample)` is called to set the current sample as an attribute:https://github.com/voxel51/fiftyone/blob/496e402db4eb2974acb12d26f4ffe926ced2d7b0/fiftyone/utils/data/parsers.py#L64

Then, the sample attributes are parsed with functions that don't take any arguments, e.g. `get_image_path`:
 https://github.com/voxel51/fiftyone/blob/496e402db4eb2974acb12d26f4ffe926ced2d7b0/fiftyone/utils/data/parsers.py#L66

I assume this is because there is a specific usecase for overriding `with_sample` on a `SampleParser`, and I'm wondering what this usecase is. I'm trying to parallelize my `SampleParser` because it potentially downloads the images from a remote if they don't exist locally, and those web requests are in dire need of parallelization. I can achieve this fairly easily but replacing [these lines](https://github.com/voxel51/fiftyone/blob/496e402db4eb2974acb12d26f4ffe926ced2d7b0/fiftyone/utils/data/parsers.py#L80-L83) with the following code:
```python
    # This is the only modification; we want to process these in parallel.
    # TODO: Make a FiftyOne PR so we can get rid of this.
    e = ThreadPoolExecutor()
    futures = [e.submit(parse_sample, sample) for sample in samples]

    # The progress bar isn't very smooth, but at least the order is preserved.
    # Alternatively, we could use as_completed and then sort the samples afterwards.
    batch_size = 128
    sample_ids = []
    with fou.ProgressBar(total=num_samples) as pb:
        for batch in fou.iter_batches(futures, batch_size):
            wait(batch)  # Wait until the futures are completed
            sample_ids.extend(
                dataset._add_samples_batch([f.result() for f in batch], expand_schema)
            )
            pb.update(count=len(batch))

    return sample_ids
```

However, the problem is that since `self.current_sample` is just a single attribute on an instance shared by all those threads, the images and their attributes will get mixed up. This could be solved easily by getting rid of `with_sample` and instead just passing the sample to e.g. `get_image_path(sample)`, but it'd remove the possibility of performing certain actions on `with_sample` by overriding it.

Curious to hear your thoughts!

### Motivation

-   What is the use case for this feature? Massive speedups in sample parsing
-   Why is this use case valuable to support for FiftyOne users in general? Any decently sized, (partially) remotely stored collection of images takes a very long time to load, and you don't necessarily want to download **all** images beforehand if you're just looking at a specific selection of them.
-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient) -> See above.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [x] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by jneeven** [comment]
> This could be solved easily by getting rid of with_sample and instead just passing the sample to e.g. get_image_path(sample), but it'd remove the possibility of performing certain actions on with_sample by overriding it.

It should actually be possible to just check if e.g. `get_image_path` has a `sample` argument, and still default to `with_sample` if it doesn't. Then that distinction is up to the implementer of the `SampleParser`. It would look something like this:
```python
def pass_sample_kwarg(function, sample):    
    if "sample" in inspect.signature(function).parameters:
        return functools.partial(function, sample=sample)
    return function
```

**Comment by brimoor** [comment]
Hey @jneeven 👋 

Thanks for doing such a thorough investigation into ways to support parallelism when loading datasets!

To answer your question first, the reason that the `SampleParser` syntax looks like this (for `LabeledImageSampleParser`, for example):

```py
sample_parser.with_sample(sample)

image_path = sample_parser.get_image_path()
label = sample_parser.get_label()
```

rather than this:

```py
# these could be static methods
image_path = sample_parser.get_image_path(sample)
label = sample_parser.get_label(sample)
```

is that certain parsers like [TFRecordSampleParser](https://github.com/voxel51/fiftyone/blob/d0b3b6315d311cf886a4bb7c486c5307b1b2c473/fiftyone/utils/tf.py#L254-L292) have the property that parsing the input `sample` (a TF record, in this case) can be expensive and thus it was desirable to let the input be parsed separately via `with_sample()` and then allow parsers to cache data internally that can be efficiently returned via `get_image_path()` and `get_label()` as requested without re-parsing the sample.

Similar to what you pointed out, if those methods were static, then it would be a pretty simple rewrite to support multithreading by replacing

https://github.com/voxel51/fiftyone/blob/d0b3b6315d311cf886a4bb7c486c5307b1b2c473/fiftyone/utils/data/parsers.py#L80-L83

with (same idea as what you showed but a bit simpler even):

```py
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        _samples = executor.map(parse_sample, samples)
        return dataset.add_samples(
            _samples, num_samples=num_samples, expand_schema=False
        )
```

The interesting challenge, as I see it, is that your use case of downloading images is network bound and thus would benefit from multithreading, but things like parsing TF examples are likely CPU bound and thus would require multiple **processes** in order to be similarly accelerated. However, in that case, I would wonder if the cost of shuttling those TF records between processes might outweigh the benefits of multiple processes...

I tried a multiple process solution (which would mitigate the threaded issues you observed because each process would get its own copy of `sample_parser`) by replacing 

https://github.com/voxel51/fiftyone/blob/d0b3b6315d311cf886a4bb7c486c5307b1b2c473/fiftyone/utils/data/parsers.py#L63-L83

with

```py
    with ThreadPoolExecutor(max_workers=num_workers) as executor:
        _samples = executor.map(parse_sample, samples)
        return dataset.add_samples(
            _samples, num_samples=num_samples, expand_schema=False
        )

    with multiprocessing.Pool(
        num_workers, _initialize_pool, (sample_parser, tags)
    ) as pool:
        _samples = pool.imap(_do_parse_sample, samples)
        return dataset.add_samples(
            _samples, num_samples=num_samples, expand_schema=False
        )


def _initialize_pool(sample_parser, tags):
    def _parse_sample(sample):
        sample_parser.with_sample(sample)

        image_path = sample_parser.get_image_path()

        if sample_parser.has_image_metadata:
            metadata = sample_parser.get_image_metadata()
        else:
            metadata = None

        return fos.Sample(filepath=image_path, metadata=metadata, tags=tags)

    global parse_sample
    parse_sample = _parse_sample


def _do_parse_sample(sample):
    return parse_sample(sample)
```

but unfortunately that doesn't work yet because our `Sample` objects are not currently picklable (news to me). Probably resolvable but would take some more tweaks.

**Comment by brimoor** [comment]
I do like your idea of finding a way to support parallelism for the `fiftyone.utils.data.parsers.add_*()` methods! If you have any thoughts on how to proceed, please do share.

**Comment by brimoor** [comment]
With all that said, have you looked into writing a [custom DatasetImporter](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#writing-a-custom-datasetimporter) rather than a [custom SampleParser](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/samples.html#writing-a-custom-sampleparser)?

The `DatasetImporter` interface is a bit higher-level  because it allows you to define an iterable that emits your sample data, rather than having to just define the parsing function as in `SampleParser`.

For example, the code below demonstrates a custom `DatasetImporter` that can download images from the web using multiple threads and feed them to FiftyOne. 

The example is mocked with `time.sleep()`, but it does what you want: it imports 200 images with ~100 seconds of `time.sleep()` involved in 100/8 = 12.5 seconds 😄 

```py

import os
import random
import time

import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone.utils.data.importers import UnlabeledImageDatasetImporter
from concurrent.futures import ThreadPoolExecutor


def download_image(url):
    # Mock image download
    time.sleep(random.random())

    return url


class WebImagesImporter(UnlabeledImageDatasetImporter):

    def __init__(self, urls, num_workers=None):
        if num_workers is None:
            num_workers = os.cpu_count()

        self.urls = urls
        self.num_workers = num_workers
        self._executor = None
        self._downloads = None

    def __len__(self):
        return len(self.urls)

    def __next__(self):
        image_path = next(self._downloads)
        return image_path, None

    @property
    def has_image_metadata(self):
        return False

    @property
    def has_dataset_info(self):
        return False

    def setup(self):
        self._executor = ThreadPoolExecutor(max_workers=self.num_workers)
        self._downloads = self._executor.map(download_image, self.urls)

    def close(self, *args):
        self._executor.shutdown()


# Get some image paths
_dataset = foz.load_zoo_dataset("quickstart").clone()
images = _dataset.values("filepath")

importer = WebImagesImporter(images, num_workers=8)

dataset = fo.Dataset.from_importer(importer)
```

**Comment by jneeven** [comment]
> With all that said, have you looked into writing a custom DatasetImporter rather than a custom SampleParser?

I had not, thanks for the suggestion! I was under the impression that that would require me to also store the images in a FiftyOne-specified hierarchy on disk, but looks like this should work without any issues :+1:

In which scenario would the `SampleParser` be preferable to the `DatasetImporter`? In the end, both require you to have the images on disk locally and provide a path for them (at least the `LabeledImages` parser does)

**Comment by brimoor** [comment]
> > With all that said, have you looked into writing a custom DatasetImporter rather than a custom SampleParser?
> 
> I had not, thanks for the suggestion! I was under the impression that that would require me to also store the images in a FiftyOne-specified hierarchy on disk, but looks like this should work without any issues 👍
> 
> In which scenario would the `SampleParser` be preferable to the `DatasetImporter`? In the end, both require you to have the images on disk locally and provide a path for them (at least the `LabeledImages` parser does)

There's not really any reason to use `SampleParser`, we should probably deprecate it at some point to avoid confusion about there being basically two ways to do the same thing. 

FYI- adding support for directly constructing FiftyOne datasets whose media paths are URLs is something that's on our roadmap for sure. Shouldn't be too hard once we get some bandwidth for it.

**Comment by jneeven** [comment]
> FYI- adding support for directly constructing FiftyOne datasets whose media paths are URLs is something that's on our roadmap for sure. Shouldn't be too hard once we get some bandwidth for it.

My images are hosted on a private server so I'd probably still need to implement this manually, but good to hear! I'll stop trying to use the `SampleParser` then, and will close this issue.
