### ISSUE TITLE
data label content and metadata are same independent of size of dataset downloaded and data downloaded

### ISSUE THREAD

**Issue by nagarjunvinukonda** [voxel51/fiftyone#1145]
Hi,

I have downloaded openimageV6 dataset using the fiftyone tool. using following code: 

import fiftyone as fo
import fiftyone.zoo as foz 

```
dataset = foz.load_zoo_dataset(
              "open-images-v6",
              split="validation",
              label_types=["detections"],
              classes=["Skateboard"],
              max_samples=100,
          )
```
I have downloaded datasets for different classes, different no.of max samples. Though the data downloaded is huge or less or different from one other the labels, metadata downloaded are the same for every same split(Ex: train,  validation, test). 

I want data labels for only my downloaded data, I don't want redundant data labels in my csv files. What should be added in the code to get necessary data labels with the data I have downloaded properly.

I hope you understood the question. I  will be glad to explain further. Looking forward to a solution. 

Also I want to download different categories of data evenly distributed, Example: If I mention 100 samples of cats, dogs, persons, tree, skateboards, etc., in fiftyone code using classes and max_samples I shall get evenly distributed data, i.e. 100 cats, 100n dogs, 100 persons, etc. Is this possible by fiftyone?

**Comment by benjaminpkane** [comment]
It's is beneficial to keep all of the csv files so that you can easily load more data only needing to download the additional media, you don't have to download the labels/metadata again. If you are certain about that subset you want, though, and don't want to store additional files, you can export the dataset in one of our provided formats, e.g. `fiftyone.types.FiftyOneDataset`, in a separate location and then delete the zoo dataset files.

Metadata that is duplicated between splits is a total of 40kb, which is negligible.

For your second question, the best way to do that now would be to download each subset separately, i.e. run `foz.load_zoo_dataset()` multiple times with `max samples=100` and specify one class at a time, and then merge the classes together. This is actually done in the [Open images tutorial.](https://voxel51.com/docs/fiftyone/tutorials/open_images.html#Loading-Open-Images)

There is no redundancy in the downloaded labels, and the current download strategy is intentional so loading various forms of Open Images is reliable, noting that we do not host the Open Images dataset.
