### ISSUE TITLE
Cannot import valid coco file using  python code

### ISSUE THREAD

**Issue by i81353** [voxel51/fiftyone#1200]
### System information

-   Linux Ubuntu 20.04
-   FiftyOne installed from pip:
-   FiftyOne version:  v0.11.1
-   **Python version**:  3.8.10

### Code to reproduce

I have created a valid COCO file, but the segmentation field is not imported. I am attaching both the image and the json file.

Code is pretty simple
```
# commands here

dataset = fo.Dataset.from_dir(dataset_dir='directory_provided_labels.json_is_contained',
                                  dataset_type=fo.types.COCODetectionDataset,
                                  name='foo_database')

    # print('Current databases: {}'.format(fo.list_datasets()))
    session = fo.launch_app(dataset=dataset, port=5151)

    input('Press enter to continue')

```
 The labels.json file containes a full path to the image. 

### Describe the problem

The file is imported, and the image  with its bounding box and  category can be seen correctly. However, we cannot see the segmentation. I have reviewed the format and it seems ok. I have also checked the dataset from code and the sample imported does not contain the segmentation in the detections field.

In the first moment I thought it could be cause because my labels.json was not ok with the standard, but I have checked multiple times and I do not see the error. Meanwhile I will try to add the information using pure code instead of a coco json file.

-   [ ] `App`: FiftyOne application issue
-   [x ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time. Sorry.
[bug_info.zip](https://github.com/voxel51/fiftyone/files/6997974/bug_info.zip)

**Comment by i81353** [comment]
I have checked another issues, the documentation says a data directory containing the images should be located in the same directory the labels.json is stored. 
I have tried it, but the results are exactly the same.
Atacching json with just the image file name and the right hierarchy.

[coco_output.zip](https://github.com/voxel51/fiftyone/files/6998064/coco_output.zip)

**Comment by brimoor** [comment]
Hi @i81353 👋 

The issue is that, by default, only bounding boxes are loaded, but you can opt-in to loading segmentations and other COCO things like license, COCO ID, etc. by passing additional parameters. This is mentioned in the `NOTE` mid-way through [this section](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cocodetectiondataset) of the docs for loading COCO data, and if you click through you'll find [this section](https://voxel51.com/docs/fiftyone/api/fiftyone.utils.coco.html#fiftyone.utils.coco.COCODetectionDatasetImporter) which documents the extra parameters you can pass to `from_dir()` to customize the import.

This documentation could probably be improved to be more easily discoverable. Apologies for that..

I was able to load your sample data like so:

```py
import fiftyone as fo

dataset = fo.Dataset.from_dir(
    dataset_dir="/path/to/coco_output",
    dataset_type=fo.types.COCODetectionDataset,
    label_types="segmentations",
)

session = fo.launch_app(dataset)
```

Note that, if you prefer, you can instead provide `data_path` and `labels_path` instead of `dataset_dir`, which allows you to independently specify the path to the JSON file and the path to the directory containing the images rather than organizing them in the "standard format" expected by FiftyOne when you use the `dataset_dir` syntax.

For example, here's another way to load in your data that stores bboxes and segmentations stored as polylines, also including licensees and coco IDs from your data:

```py
dataset = fo.Dataset.from_dir(
    data_path="/path/to/images",
    labels_path="/path/to/coco_output/labels.json",
    dataset_type=fo.types.COCODetectionDataset,
    label_types=["detections", "segmentations"],
    include_id=True,
    include_license=True,
    use_polylines=True,
)
```

**Comment by i81353** [comment]
Thank you very much. It worked. Now I have a way to import my dataset information into fiftyone.  

In the meantime I've been able to import the information programmatically. I had some minor issues, I had to figure out that the segmentation mask had to reference the bounding box, not to use global image coordinates, but it was ok.

I will close the issue now.

Thank you again for your quick response.
