### ISSUE TITLE
[BUG] Unable to download train split of dataset

### ISSUE THREAD

**Issue by dosterz97** [voxel51/fiftyone#1230]
### System information

-   macOS Big Sur 11.3.1:
-  Installed from pip
-  fiftyone version 0.13.1:
-   python 3.8.2:

### Commands to reproduce

Only running this line of code in a python file
```
# commands here
python ./fiftyone.py
```

### Describe the problem
I cannot load a dataset for any "train" split for any classes. The validation set works just fine.

The download hangs and does nothing with this 

```
/Users/zach/.local/share/virtualenvs/headphones-rcOaot1v/lib/python3.8/site-packages/fiftyone/utils/openimages.py:1146: DtypeWarning: Columns (5) have mixed types.Specify dtype option on import or set low_memory=False.
  df = _parse_csv(csv_path, dataframe=True)
```
  
  I didnt have this issue when i was on fiftyone==0.11.2.1

```
dataset = fo.zoo.load_zoo_dataset(
        "open-images-v6",
        split="train",
        label_types=["detections"],
        classes=["Glasses"],
        num_workers=1,
    )
```

### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [ X] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ X] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hi @dosterz97, the train split of Open Images V6 is *really big*. The full train split has 500+ GB of images, and just the detections CSV file is 2.1GB.

Even though you're specifying `classes=["Glasses"]`, so that only images containing glasses will be downloaded (<< 500GB), in order for FiftyOne to figure out what images to download, it first needs to load the 2.1GB detections CSV into memory. That's what the `_parse_csv()` function in your snippet is doing. [The code](https://github.com/voxel51/fiftyone/blob/e43c00ab96282d1f016e4f57f806c8f48feff6bc/fiftyone/utils/openimages.py#L812-L826) uses pandas for that, and it has not been optimized by declaring column types, so it likely requires >2.1 GB of memory. It's likely that you're either running out of RAM on your machine or you just need to let in run longer to do the parsing (it takes ~2-3 minutes on my machine).

I ran your snippet like so:

```py
import fiftyone as fo

dataset = fo.zoo.load_zoo_dataset(
    "open-images-v6",
    split="train",
    label_types=["detections"],
    classes=["Glasses"],
    num_workers=1,
)
```

And let it run until just after the CSV was parsed and it started to download the images:

```
Downloading split 'train' to '/Users/Brian/fiftyone/open-images-v6/train' if necessary
Downloading 'https://storage.googleapis.com/openimages/2018_04/train/train-images-boxable-with-rotation.csv' to '/Users/Brian/fiftyone/open-images-v6/train/metadata/image_ids.csv'
 100% |█████████████████████████████████|    4.8Gb/4.8Gb [16.5s elapsed, 0s remaining, 280.9Mb/s]      
Downloading 'https://storage.googleapis.com/openimages/v5/class-descriptions-boxable.csv' to '/Users/Brian/fiftyone/open-images-v6/train/metadata/classes.csv'
Downloading 'https://storage.googleapis.com/openimages/2018_04/bbox_labels_600_hierarchy.json' to '/var/folders/gh/h2wv5n5d4kz4dblxqzgw703c0000gp/T/tmpocpaec1d/metadata/hierarchy.json'
Downloading 'https://storage.googleapis.com/openimages/v6/oidv6-train-annotations-bbox.csv' to '/Users/Brian/fiftyone/open-images-v6/train/labels/detections.csv'
Downloading 41945 images
   0% ||------------------------------------------------------------------|    75/41945 [15.7s elapsed, 2.4h remaining, 3.2 images/s]
```

So for me it ran, on a macbook with 16GB of RAM, which seems like a reasonable lower bound on available RAM for working with a massive dataset like Open Images.

The warning you printed suggests that the `low_memory=False` option could be passed to `pd.read_csv()` in the code I linked above, which may resolve the issue for you. Can you check by doing a [source install](https://github.com/voxel51/fiftyone#installing-from-source) and making the change? The project is open source, so PRs are welcome 😄 

Here's a [stack overflow post](https://stackoverflow.com/questions/24251219/pandas-read-csv-low-memory-and-dtype-options) on the matter. One can likely speed up the loading of that file significantly by declaring dtypes beforehand, but its a bit of a low priority to optimize that because 2 minutes is a drop in the bucket compared to the time required to download the images next.

**Comment by dosterz97** [comment]
Thanks @brimoor for the quick help. I just didn't wait long enough. Thanks for the links I don't think this needs anymore attention but it should help others in the future!
