### ISSUE TITLE
[FR] Opening the expanded view during grid selection

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#1232]
Per user feedback, it would be useful if one could still open the expanded sample view even during grid selection. `Ctrl + click` could be used to override the default click selection when in selection mode in  the grid.

**Comment by brimoor** [comment]
A corollary to this is that we'll want/need to expose the ability to select samples from the expanded modal (currently only labels can be selected) and persist information about currently selected samples so that multi-sample-tagging workflows can be continued and/or completed with the expanded sample modal open.
