### ISSUE TITLE
Cityscapes Label Data not importing correctly [BUG]

### ISSUE THREAD

**Issue by ShaneGilroy** [voxel51/fiftyone#1252]
### Commands to reproduce

```py
# Load Citypersons Dataset

import fiftyone as fo
import fiftyone.zoo as foz

# The path to the source files that you manually downloaded
source_dir = "/Users/gilro/Desktop/Datasets/Cityscapes"

dataset = foz.load_zoo_dataset(
    "cityscapes",
    split="validation",
    source_dir=source_dir,
    person_annos=True,
    fine_annos=True,
)

session = fo.launch_app(dataset)
```

### Describe the problem

**When loading the Citypersons dataset, labels are not loaded with the images**. The directory is set up as instructed in the documentation and the "person_annos" parameters are forced to true. 

### Code to reproduce issue

```py
import fiftyone as fo
import fiftyone.zoo as foz

source_dir = "/Users/gilro/Desktop/Datasets/Cityscapes"

dataset = foz.load_zoo_dataset(
    "cityscapes",
    split="validation",
    source_dir=source_dir,
    person_annos=True,
    fine_annos=True,
)

session = fo.launch_app(dataset)
```

Provide a reproducible test case that is the bare minimum necessary to generate
the problem.

### Other info / logs

Source directory set up as instructed below:

![image](https://user-images.githubusercontent.com/38457008/132221021-4e1a0612-f72e-4322-9d8b-00c189b42360.png)

Output - "No Label Fields" as below:

![image](https://user-images.githubusercontent.com/38457008/132221120-be5994b3-363f-46e5-91a5-c6515e565f65.png)

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and
files should be attached.

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
@ShaneGilroy When I run the code you shared the dataset loads properly.

I took a look at [the docs page](https://voxel51.com/docs/fiftyone/user_guide/dataset_zoo/datasets.html#dataset-zoo-cityscapes) and I suspect the issue is that in:

```
source_dir/
    leftImg8bit_trainvaltest.zip
    gtFine_trainvaltest.zip         # optional
    gtCoarse.zip                    # optional
    gtBbox_cityPersons_trainval     # optional
```

`gtBbox_cityPersons_trainval.zip` is missing `.zip`. If you removed `.zip` from your version of the files then FiftyOne wouldn't find the file it expected, and thus it wouldn't load the annotations as you requested.

**Comment by ShaneGilroy** [comment]
Hi Brian,

No, I noticed that the documentation left out the .zip extension and I have the full zip file in my folder. Have you been able to recreate the issue?

**Comment by brimoor** [comment]
No I can't reproduce. Installing the latest version of FiftyOne:

```
pip install --upgrade fiftyone
```

with the Cityscapes files in a directory like so:

```
$ ls -lah /data1/home/brian/fiftyone-datasets/cityscapes/source/
total 13G
drwxrwxr-x 2 brian brian 4.0K Sep  8 09:11 .
drwxrwxr-x 4 brian brian 4.0K Sep  8 09:13 ..
-rw-rw-r-- 1 brian brian 2.2M Sep  8 09:10 gtBbox_cityPersons_trainval.zip
-rw-rw-r-- 1 brian brian 1.3G Sep  8 09:11 gtCoarse.zip
-rw-rw-r-- 1 brian brian 241M Sep  8 09:11 gtFine_trainvaltest.zip
-rw-rw-r-- 1 brian brian  11G Sep  8 09:10 leftImg8bit_trainvaltest.zip
```

Then running the code below loads the dataset with annotations as expected:

```py
import fiftyone as fo
import fiftyone.zoo as foz

# The path to the source files that you manually downloaded
source_dir = "/data1/home/brian/fiftyone-datasets/cityscapes/source"

dataset = foz.load_zoo_dataset(
    "cityscapes",
    split="validation",
    source_dir=source_dir,
    person_annos=True,
    fine_annos=True,
)

session = fo.launch_app(dataset)
```

**Comment by brimoor** [comment]
Can you upgrade your FiftyOne installation if necessary?

If you previously had `gtBbox_cityPersons_trainval` instead of `gtBbox_cityPersons_trainval.zip` and then ran `load_zoo_dataset()`, you might have loaded a version of the dataset without annotations. If you then made that dataset persistent, re-running the same `load_zoo_dataset(...)` command wouldn't reload the dataset, it would just load the existing one.

So, to further flush out your system, make sure you delete any existing dataset called `cityscapes-validation`.

One more thing to try would be to delete the existing unpacked files from previous times you loaded the cityscapes dataset. To see where these files are, run `fiftyone config` in your shell, then delete the `${dataset_zoo_dir}/cityscapes` directory on your machine.

**Comment by brimoor** [comment]
I'm guessing `delete_zoo_dataset()` will do the trick for you, because, if I run the following from a fresh environment:

```py
dataset = foz.load_zoo_dataset(
    "cityscapes",
    split="validation",
    source_dir=source_dir,
    person_annos=False,
    fine_annos=False,
    coarse_annos=False,
)
```

to load only the images, then running:

```py
dataset = foz.load_zoo_dataset(
    "cityscapes",
    split="validation",
    source_dir=source_dir,
)
```

immediately after will not load any annotations, because the dataset has already been "prepared" without annotations. But if I insert

```py
foz.delete_zoo_dataset("cityscapes", split="validation")
```

in between then I'll get the annotations I wanted the second time.

**Comment by ShaneGilroy** [comment]
Hi Brian,

Thanks for the feedback. I uninstalled fiftyone, fiftyone desktop and all related folders and done a complete new installation and it done the trick. 

Thanks
