### ISSUE TITLE
[FR] Please consider upgrading mongoDB to 5.0

### ISSUE THREAD

**Issue by robmarkcole** [voxel51/fiftyone#1268]
### Proposal Summary
I would assume this is in the pipeline, but perhaps there are backwards compatibility issues. I am on an M1 mac and despite following the docs am unable to get mongodb-community@4.4 running. However mongodb-community@5.0 runs without issue.

**Comment by brimoor** [comment]
Hi @robmarkcole 👋 

Just to be clear, you're saying that you found [these instructions](https://voxel51.com/docs/fiftyone/user_guide/config.html#configuring-mongodb-connection) but unfortunately you're having issues getting MongoDB v4.4 installed and running yourself?

[This user](https://github.com/voxel51/fiftyone/issues/1165) seemed to indicate that `brew install mongodb-community@4.4` was sufficient, but I was a little surprised about that because I was under the impression that compiling with Rosetta may also be required. Unfortunately I don't have access to an M1 mac to test that.

The user in the above issue also reported issues with other packages like `scikit-image` and `sciki-learn` that seemingly also might be blockers for getting FiftyOne running on M1 macs.

Upgrading to MongoDB v5 is definitely something that we can consider. It was only released July 13th and we haven't started investigating if there are any breaking changes in the new version, but I'm guessing it shouldn't be too much of an issue. Although we warn that we need MongoDB v4.4, that's mostly because are using v4.4 features and so earlier versions will not work. However, I wouldn't be surprised if you can use a MongoDB v5 database now, especially if you [set the feature compatibility version](https://docs.mongodb.com/manual/reference/command/setFeatureCompatibilityVersion) to v4.4 on your database:

```
db.admin.command({"setFeatureCompatibilityVersion": "4.4"})
```

You would probably need to be running a [source install](https://github.com/voxel51/fiftyone#installing-from-source) to do that though, as you would need to edit [this line](https://github.com/voxel51/fiftyone/blob/5063f248a247ffc4a8f56d2d19201d3a190527e4/fiftyone/constants.py#L80) to make FiftyOne allow you to use MongoBD v5.

**Comment by robmarkcole** [comment]
I was able to `brew install mongodb-community@4.4` as well as 5.0, but there was an issue running 4.4 whilst 5.0 ran without issue. RE skimage and sklearn I am regularly using them on M1, so this appears resolved nowadays. 

I will now try the edit you suggest

**Comment by brimoor** [comment]
I was able to install MongoDB v5 and successfully load the quickstart dataset in the App.

Here's what I did (on an Intel Mac):

Edit code like you did:

```
MONGODB_VERSION_RANGE = (Version("4.4"), Version("5.1"))  # [min, max)
```

Then in first shell:

```
brew tap mongodb/brew
brew install mongodb-community@5.0

DB_DIR=/path/for/db
mkdir -p $DB_DIR

mongod --dbpath $DB_DIR --port 12345
```

Then in second shell:

```
mongo --port 12345 --shell

db.adminCommand({setFeatureCompatibilityVersion: "4.4"})
db.adminCommand({getParameter: 1, featureCompatibilityVersion: 1})
# exit
```

```
export FIFTYONE_DATABASE_URI=mongodb://localhost:12345
```

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")
session = fo.launch_app(dataset)
```

**Comment by brimoor** [comment]
Using a non-default port wasn't necessary (the default is 27019), and using a non-default database directory probably wasn't necessary either, although I recommend it because you might run into problems if you use that MongoDB install for other things

**Comment by robmarkcole** [comment]
OK so as far as I can see `mongodb-community@5.0` is compatible

**Comment by brimoor** [comment]
Good to know 👍 

For now, I'll make a quick PR to allow MongoDB v5 to be used without code changes like we've just done, and then we'll look into upgrading the default MongoDB build to v5 as a separate item.

**Comment by brimoor** [comment]
FYI for anyone reading this, `fiftyone==0.13.3` added support for using a self-installed MongoDB version whose version is not explicitly supported by FiftyOne (at your own risk).

Instructions for this are here: https://voxel51.com/docs/fiftyone/user_guide/config.html#using-a-different-mongodb-version.

**Comment by swheaton** [comment]
stale, mongo 5 works
