### ISSUE TITLE
[FR] Ability to specify AND instead of OR for classes when loading the COCO dataset

### ISSUE THREAD

**Issue by daveisfera** [voxel51/fiftyone#1295]
### Proposal Summary

Currently, the list of classes is an `OR` but it would be nice if there was a way to have the list be an `AND` instead

### Motivation

Provides a way to limit the images to just those with 2 or more classes in them. Currently, it's only possible to get the images that have any of the classes, so there's no way to limit the data in this useful way.

### What areas of FiftyOne does this feature affect?
-   [ ] App: FiftyOne application
-   [X] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

The data to do this is already available in the code ( see line to code below ) and `all_ids` will technically be a subset of `any_ids` so combining them really only has a benefit when `shuffle=True`
https://github.com/voxel51/fiftyone/blob/e911fb084850f97fa392ab29701f8e471e131e9a/fiftyone/utils/coco.py#L1560

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [X] Yes. I can contribute this feature independently.
-   [X] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [ ] No. I cannot contribute this feature at this time.

**Comment by brimoor** [comment]
Hi @daveisfera 👋 

You can achieve "AND" matching using [dataset views](https://voxel51.com/docs/fiftyone/user_guide/using_views.html#filtering) as follows:

```py
import fiftyone as fo
import fiftyone.zoo as foz
from fiftyone import ViewField as F

dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="validation",
    classes=["cat", "dog"],
)

cats_and_dogs = dataset.match(
    (F("ground_truth.detections").filter(F("label") == "cat").length() > 0)
    & (F("ground_truth.detections").filter(F("label") == "dog").length() > 0)
)

session = fo.launch_app(view=cats_and_dogs)
```

Admittedly, this does require downloading all images that contain any of the classes of interest first, so that you can then do the "OR" matching once the data is in FiftyOne.

It's tempting to add an extra parameter to `load_zoo_dataset()` to directly expose "AND" behavior. As you point out, it so happens that the logic already exists in the code. However, I tend to think we shouldn't pull the trigger, mostly on principle, for the following reasons:
- We like to encourage loading data into FiftyOne first, since that exposes a rich query language that supports sophisticated filtering operations far beyond "AND"/"OR" class matching
- Adding filtering operations at download-time doesn't scale to other zoo datasets; it must be re-implemented for each dataset. We did set a precedent that COCO and Open Images are "special" by supporting the `classes` syntax in the first place (partial downloads), but I'd like to minimize extra customizations if possible 
- In general, I would expect "AND" class matching to only make sense when the class list is quite small (even cats and dogs only appear together 12 times in the COCO validation split, for example). So maybe it's not so bad to do downloads with "OR" matching so that you have a few more samples available for inspection in case you need more data :)

**Comment by brimoor** [comment]
The syntax I showed for AND matching was a bit ugly, but once https://github.com/voxel51/fiftyone/pull/1301 is in, one can just do:

```py
cats_and_dogs = dataset.match(F("ground_truth.detections.label").contains(["cat", "dog"], all=True))
```

**Comment by daveisfera** [comment]
Thanks for sending that over and it's nice to see that it's possible with the current setup. Also, working with the whole dataset makes sense and definitely would make things faster for future activities, but if all you care about is that subset of data, then it means that a large amount of data needs to be downloaded that won't be used.
For example, the number of images in COCO that have both a dog and a cat is 208 but then the number that have a dog or a cat is 8083. That means that the majority of that download will be a waste and it would be nice to have a way to avoid that when a user has that sort of use case.
