### ISSUE TITLE
Is it possible to pass the original filenames to CVAT?

### ISSUE THREAD

**Issue by niclaswue** [voxel51/fiftyone#1432]
When uploading the images from fiftyone to CVAT, the filenames are lost. When syncing with a dataset repository, however, they are crucial as there is no other way of getting the original filenames to the annotations. I think #1235 could possibly fix this, if it was implemented. Are there currently any other workarounds? The labeling order in a given task in CVAT is not important to me.

**Comment by ehofesmann** [comment]
Good call, the original filenames should be retained somehow when media is uploaded to CVAT. There is an issue in that CVAT automatically reorders media alphabetically by filename which is why we changed the filenames, to begin with. 

#1433 changes this to simply prepend the integer value to the filename so it can be sorted correctly and the original filename is still available.

**Comment by niclaswue** [comment]
Ah I see, that's a nice and simple solution. Thank you for creating a PR :+1:
