### ISSUE TITLE
[BUG] Reserved attribute name discrepancy

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#1462]
Note the discrepancy below:

```py
import fiftyone as fo

# works
sample = fo.Sample(filepath="image.png", objects="object")
dataset = fo.Dataset()
dataset.add_sample(sample)

# works
dataset = fo.Dataset()
dataset.add_sample_field("objects", fo.StringField)

# error
sample = fo.Sample(filepath="image.png")
dataset = fo.Dataset()
dataset.add_sample(sample)
sample["objects"] = "object"
```

**Comment by brimoor** [comment]
There's at least one place in the documentation that should be updated once this is addressed:

<img width="771" alt="Screen Shot 2021-12-07 at 7 11 31 PM" src="https://user-images.githubusercontent.com/25985824/145125418-74648bd2-d399-43cf-a77d-ff434d2c406a.png">

**Comment by brimoor** [comment]
Update: as per https://github.com/voxel51/fiftyone/pull/1469, I think the proper way for us to address this will be to update our `Document` classes so that fields can have arbitrary names and can always be accessed via `document[field]`, and `document.field` will default to a class method rather than user-defined fields (eg `field="to_dict"`) in the case of a clash.

Unfortunately, this is not easily achievable until we get rid of MongoEngine.
