### ISSUE TITLE
[FR] Keypoint display

### ISSUE THREAD

**Issue by joihn** [voxel51/fiftyone#1466]
I have a COCO format dataset with keypoint, but I can't find a way to display the keypoints. 
Is this a missing feature ? If yes it would be a nice addition

**Comment by brimoor** [comment]
Hi @joihn 👋 

By default, when you load COCO-formatted data using [COCODetectionDataset](https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#cocodetectiondataset) format, only bounding boxes are used.

However, you can pass the optional `label_types` parameter to methods like `from_dir()` in order to specify that keypoint data should be loaded. For example:

```py
import fiftyone as fo

dataset = fo.Dataset.from_dir(
    data_path="/path/to/images",
    labels_path="/path/to/coco.json",
    dataset_type=fo.types.COCODetectionDataset,
    label_types=["keypoints"],
)

session = fo.launch_app(dataset)
```

[Here's the docs](https://voxel51.com/docs/fiftyone/api/fiftyone.utils.coco.html#fiftyone.utils.coco.COCODetectionDatasetImporter) for the optional parameters you can pass when importing COCO data.

**Comment by joihn** [comment]
thanks a lot for the quick and helpfull answer :)
