### ISSUE TITLE
[?] Need help with manifest.json file when adding a custom model to FiftyOne

### ISSUE THREAD

**Issue by valentindbdg** [voxel51/fiftyone#1475]
Hello, I am trying to add my yolo v3 model to the local model zoo.
I am using google colab. In the manifest I added the fields below and I was wondering what is the field "google_drive_id": ?
Should I add the id of a shared .weights file from my google drive?

Thank you for your answer.

```
{
    "models": [
        {
            "base_name": "yolov3-tiny",
            "base_filename": "yolov3-tiny_best.weights",
            "version": null,
            "description": "A YOLOv3 model",
            "manager": {
                "type": "fiftyone.core.models.ModelManager",
                "config": {
                    "google_drive_id": "1ajuPZws47SOw3xJc4Wvk1yuiB3qv8ycr"
                }
            },
            "default_deployment_config_dict": {
                "type": "fiftyone.utils.eta.ETAModel",
                "config": {
                    "type": "eta.detectors.YOLODetector",
                    "config": {
                        "config_dir": "{/content/drive/MyDrive/yolov3-model",
                        "config_path": "{/content/drive/MyDrive/yolov3-model/yolov3-tiny.cfg",
                    }
                }
            },
            "requirements": {
                "cpu": {
                    "support": true,
                    "packages": ["tensorflow<2"]
                },
                "gpu": {
                    "support": true,
                    "packages": ["tensorflow-gpu<2"]
                }
            },
            "tags": ["detection", "coco", "tf1"],
            "date_added": "2021-12-14 13:45:51"
        }
    ]
}
```

**Comment by brimoor** [comment]
Hey @valentindbdg 👋 

So you're interested in following [these instructions](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/api.html#adding-models-to-the-zoo) to add your own custom model to your local model zoo so that you can use it with methods like [load_zoo_model()](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/zoo/models/__init__.py#L152) and [apply_model()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.dataset.html#fiftyone.core.dataset.Dataset.apply_model).

At a high-level, there are two key pieces to this:

**1) Defining the model**

To use your own custom model with methods like [apply_model()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.dataset.html#fiftyone.core.dataset.Dataset.apply_model), you need to:

- Write a subclass of [Model](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/core/models.py#L1531) that performs the inference
- Write a subclass of [ModelConfig](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/core/models.py#L1519) that defines the parameters that your model takes

If you do this, then you can load your model yourself and then pass it to [apply_model()](https://voxel51.com/docs/fiftyone/api/fiftyone.core.dataset.html#fiftyone.core.dataset.Dataset.apply_model). The model zoo hasn't come into play yet.

**2) Adding a model to your local model zoo**

The [FiftyOne Model Zoo](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/index.html) provides a mechanism for defining how to download a model's weights and then construct its  `Model` instance so that it can be used by FiftyOne.

If you register your own model in the zoo by following [these instructions](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/api.html#adding-models-to-the-zoo), then you can call methods like [load_zoo_model()](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/zoo/models/__init__.py#L152) on any machine and your model will automatically be downloaded and loaded.

To register your own model, you need to:

- Write a subclass of [ModelManager](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/core/models.py#L1773) that defines how to download the model
- Write a subclass of [ModelManagerConfig](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/core/models.py#L1752) that defines the parameters that your manager accepts

**Registering the model**

With 1 and 2 in-hand, you can now register your own zoo model as follows:

The elements of the `models` list in the JSON are serialized [ZooModel](https://voxel51.com/docs/fiftyone/api/fiftyone.zoo.models.html#fiftyone.zoo.models.ZooModel) instances, and the two fields that need explaining are probably `manager` and `default_deployment_config_dict`.

`manager.type` specifies the name of your `ModelManager` class, and `manager.config` is a dict of parameters for your `ModelManagerConfig` class.

`default_deployment_config_dict.type` is the name of your `Model` class, and `default_deployment_config_dict.config` is a dict of default settings for your `ModelConfig` class to load the model.

**Concrete examples/starting points**

With all that said, if your custom model is a Torch model, you may not need to actually implement any classes, because FiftyOne already contains some pretty general purpose classes for downloading and using Torch models:

- [fiftyone.utils.torch.TorchImageModel](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/utils/torch.py#L186)
- [fiftyone.utils.torch.TorchImageModelConfig](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/utils/torch.py#L92)

Getting to your concrete question, FiftyOne also provides a basic `ModelManager` implementation that can either download model weights from a URL (if you provide the `url` parameter) or from a public file in Google Drive (if you provide the `google_drive_id` parameter):

- [fiftyone.core.models.ModelManager](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/core/models.py#L1773)
- - [fiftyone.core.models.ModelManagerConfig](https://github.com/voxel51/fiftyone/blob/06975961f5ee649dd36429feb21c959dfc0744ed/fiftyone/core/models.py#L1752)
