### ISSUE TITLE
[BUG] Cannot download large zoo dataset to mounted Google Drive from Colab

### ISSUE THREAD

**Issue by mariyapeeva** [voxel51/fiftyone#1488]
### System information

-   **OS Platform and Distribution**:  Colab Pro+ Linux 5.4.144+ x86_64 x86_64 x86_64 GNU/Linux
-   **FiftyOne installed from (pip or source)**: pip
-   **FiftyOne version (run `fiftyone --version`)**: FiftyOne v0.14.2
-   **Python version**: Python 3.7.12

### Commands to reproduce

```
# commands here

!pip install fiftyone
```
### Describe the problem

On a second run of the code below on Colab Pro+ (after the first session terminates), all images get downloaded to the home directory of Google Drive ("/content/drive/MyDrive") instead of the specified directory ("/content/drive/MyDrive/data/raw/OID"). 

As a result, it is impossible to mount Drive again. It times out because of too many files listed in the home directory (/content/drive/MyDrive). The only solution is to move all images to a folder on Drive (manually or via the Google Drive API).

### Code to reproduce issue
```
from google.colab import drive
drive.mount('/content/drive')

import fiftyone as fo
import fiftyone.zoo as foz

train = foz.load_zoo_dataset("open-images-v6", split="train", label_types=["classifications", "detections"], dataset_dir="/content/drive/MyDrive/data/raw/OID")
```
### What areas of FiftyOne does this bug affect?

-   [ ] `App`: FiftyOne application issue
-   [x] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [ ] No. I cannot contribute a bug fix at this time.

**Comment by brimoor** [comment]
Hey @mariyapeeva, I don't think this is something that can be addressed within FiftyOne. My suspicion is that it's just not feasible to store a very big dataset like the train split of Open Images using `google.colab.drive.mount()`. It's too many files to store in Google Drive, which isn't really designed for random access to that many files (hence the too many files error you saw).

Can you mount a GCS or S3 bucket instead?

I can't see any reason in the code why `load_zoo_dataset()` would ignore a custom `dataset_dir` argument that you pass.

One comment though; if a dataset is successfully created in a persistent Colab environment, you can [make the dataset persistent](https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#dataset-persistence) and then load it in future sessions via `load_dataset()`, rather than running `load_zoo_dataset()` again to construct the FiftyOne dataset from scratch.

**Comment by mariyapeeva** [comment]
It does seem to be a Drive related issue - either with listing too many files or exceeding the traffic limit. The problem is that FiftyOne downloads too many images in the home directory instead of terminating, which completely blocks Drive from mounting afterwards. This has been resolved now though - I have moved all images to a new directory with the Drive API. Thanks!
