### ISSUE TITLE
[?] How can I find duplicate samples in my dataset?

### ISSUE THREAD

**Issue by DietDietDiet** [voxel51/fiftyone#1567]
### Instructions

Thank you for submitting an issue. Please refer to our
[issue policy](https://www.github.com/voxel51/fiftyone/blob/develop/ISSUE_POLICY.md)
for information on what types of issues we address.

**Please fill in this template to ensure a timely and thorough response.**

-   Place an "x" between the brackets next to an option if it applies. Example:
    -   [x] Selected option
-   Please delete this section (all content above this line) before submitting
    the issue

### Proposal Summary

(In a few sentences, provide a clear, high-level description of the feature
request)

### Motivation

-   What is the use case for this feature?
-   Why is this use case valuable to support for FiftyOne users in general?
-   Why is this use case valuable to support for your project(s) or
    organization?
-   Why is it currently difficult to achieve this use case? (please be as
    specific as possible about why related FiftyOne features and components are
    insufficient)

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

(Use this section to include any additional information about the feature. If
you have a proposal for how to implement this feature, please include it here.)
I am using the image uniqueness feature to remove some duplicated images from my dataset. After the uniqueness scores computed, say, [A1 and A2], [B1 and B2] are similar images, and have low uniqueness scores, and I want to keep exactly number of A and B's (determined by their distributions, 1 in this case, but might be different). If I set a uniqueness threshold to filter, will all A and B's be removed from my datasets?  If so, How am I supposed to know A1 is similar to A2, B1 is similar to B2, not A1 is similar to B1 after calling uniqueness function to remove the duplicates and keep the rest?

### Willingness to contribute

The FiftyOne Community encourages new feature contributions. Would you or
another member of your organization be willing to contribute an implementation
of this feature?

-   [ ] Yes. I can contribute this feature independently.
-   [ ] Yes. I would be willing to contribute this feature with guidance from
        the FiftyOne community.
-   [x] No. I cannot contribute this feature at this time.

**Comment by ehofesmann** [comment]
Uniqueness is a scalar that is populated on every sample to indicate how unique it is with respect the rest of the dataset. It is best used for finding subsets of data that are the most unique when initially constructing a training dataset.

In order to specifically find duplicates, you should use the [visual similarity](https://voxel51.com/docs/fiftyone/user_guide/brain.html#visual-similarity) method of the FiftyOne Brain instead. It provides a method to then automatically [`find_duplicates()`](https://voxel51.com/docs/fiftyone/api/fiftyone.brain.similarity.html#fiftyone.brain.similarity.SimilarityResults.find_duplicates).

```python
import fiftyone as fo
import fiftyone.brain as fob
import fiftyone.zoo as foz

# Load dataset
dataset = foz.load_zoo_dataset("quickstart")

# Index images by similarity
results = fob.compute_similarity(dataset, brain_key="image_sim")

# Tag the most similar 10% of the dataset as duplicates
results.find_duplicates(fraction=0.1)

# Visualize the duplicate samples
sample_ids = results.duplicate_ids()
view = dataset.select(sample_ids)

session = fo.launch_app(view=view)
```

You can also provide a `thresh` to `find_duplicates()` instead of the `fraction`.

**Comment by DietDietDiet** [comment]
Thanks for the quick reply.
My expectation is to not only find the duplicates, but also clean my dataset. Just as the example mentioned above, I have a bunch of duplicated ids with low scores, [A1, A2, B1, B2], how do I know A1 is similar to A2 in order to keep exactly 1 A and 1 B and remove the rest?

**Comment by ehofesmann** [comment]
Sure thing! Using only uniqueness, there isn't a great way to know that A1 is similar to A2 rather than B1 or B2 since uniqueness is just a single scalar value without the information of what sample A1 is similar to. That is where the `compute_similarity` comes in that lets you actually compare the exact samples that are most similar to A1.

In addition to `find_duplicates()` you can also [`sort_by_similarity()`](https://voxel51.com/docs/fiftyone/user_guide/brain.html#image-similarity) to find the exact samples that are most similar to a sample of interest. This would be how to figure out if A2 is similar to A1 specifically. Sorting by similarity also lets you view similar samples at the click of a button in the App to help you clean your dataset: https://voxel51.com/docs/fiftyone/user_guide/app.html#sorting-by-visual-similarity

**Comment by brimoor** [comment]
@DietDietDiet `find_duplicates()` in conjunction with the `neighbors_map` property of the results is what you want:

```py
results.find_duplicates(fraction=0.01)
print(results.neighbors_map)
```

The `neighbors_map` property of the results object provides a data structure that summarizes the findings. The keys of the dictionary are the sample IDs of each nearest non-duplicate image, and the values are lists of (id, distance) tuples listing the sample IDs of the duplicate images for each in-sample image together with the embedding distance between the two images:

```
{
    '61143408db40df926c571a6b': [
        ('61143409db40df926c573075', 5.667297674385298),
        ('61143408db40df926c572ab6', 6.231051661334058)
    ],
    '6114340cdb40df926c577f2a': [
        ('61143408db40df926c572b54', 6.042934361555487)
    ],
    '61143408db40df926c572aa3': [
        ('6114340bdb40df926c5772e9', 5.88984758067434),
        ('61143408db40df926c572b64', 6.063986454046798),
        ('61143409db40df926c574571', 6.10303338363576),
        ('6114340adb40df926c5749a2', 6.161749290179865)
    ],
    ...
}
```

Example usage:
https://voxel51.com/docs/fiftyone/user_guide/brain.html#finding-near-duplicate-images
