### ISSUE TITLE
[BUG] YOLOv5DatasetImporter yields empty classes dict

### ISSUE THREAD

**Issue by ztyree42** [voxel51/fiftyone#1715]
Issue is self explanatory. Using Dataset.from_dir w/ type YOLOv5Dataset yields a fiftyone dataset with empty classes dict.

Use case:

I want to call add_dir on 2 separate yolo datasets and create a combined dataset and re-export to yolov5 (creating the appropriately re-indexed labels) but cannot do so as add_dir has no class dicts to merge.

**Comment by brimoor** [comment]
Hi @ztyree42, here's an example that reproduces the issue:

```py
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

# Create two datasets
dataset[:10].export(
    export_dir="/tmp/dataset1",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
)
dataset[10:20].export(
    export_dir="/tmp/dataset2",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
)

# Import datasets
dataset = fo.Dataset()
dataset.add_dir(
    "/tmp/dataset1",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
)
dataset.add_dir(
    "/tmp/dataset2",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
)
```

And here's two possible solutions:

**Solution 1**
Clear `default_classes` property before exporting. With no `classes` or `default_classes` properties set on the dataset, all available labels will be exported

```py
dataset.default_classes = None

dataset.export(
    "/tmp/dataset3",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
)
```

**Solution 2**
Manually pass the desired `classes` list to the `export()` method. This will override 

```py
classes = dataset3.distinct("ground_truth.detections.label")

dataset.export(
    "/tmp/dataset4",
    dataset_type=fo.types.YOLOv5Dataset,
    label_field="ground_truth",
    classes=classes,
)
```

You're not the first person who's encountered unexpected behavior due to the `Dataset.default_classes` and/or `Dataset.classes` properties silently being passed to methods like `export()`. We need to remove that and instead assume that the user wants to export everything in the collection by default!

**Comment by ztyree42** [comment]
Amazing, thank you so much :) I don't even want to show you the hack I
settled on lol.

**Comment by brimoor** [comment]
Haha you're not the first to be tripped up by `dataset.default_classes` 😅 

I've been meaning to change this for awhile but you finally motived me to create the issue and actually make the change! https://github.com/voxel51/fiftyone/issues/1722
