### ISSUE TITLE
[BUG] I have been converting my fiftyone dataset into a coco dataset on colab but the converted folder confuses me, it doesn't display anything pretty much. I don't understand what is going on

### ISSUE THREAD

**Issue by sp01186** [voxel51/fiftyone#1772]
### System information

-   **Google colab**:
-   **!pip install fiftyone**:
-   **Current version of fiftyone**:
-   **Python version 3.7**:

### Commands to reproduce

dataset = foz.load_zoo_dataset(
              "open-images-v6",
              split="train",
              label_types=["detections", "classifications"],
              classes=["Airplane","Cat", "Dog"],
              max_samples=2500,
          )

!fiftyone convert \
    --input-dir /root/fiftyone/open-images-v6/train --input-type fiftyone.types.FiftyOneImageDetectionDataset \
    --output-dir /tmp/fiftyone/open_images-v6-coco --output-type fiftyone.types.COCODetectionDataset

### Describe the problem

In the /tmp/fiftyone/open_images-v6-coco folder, I am expecting a bunch of data and an accurate json file. Instead I have json file that gives almost no information and I have no data in the folder. 

![Sadness](https://user-images.githubusercontent.com/58943663/169934454-7afdb3e4-a813-4e2b-b7a2-c27a9972cd02.PNG)

I am sorry for contacting you guys this way but I have become desperate and I don't know where to go for help regarding the uses of fiftyone. I want to convert the dataset to a coco dataset, ideally into a JSON file and it is being weird. It looks like it's supposed to work but it doesn't. You guys can delete this as soon as you guys see this as I can imagine this is very unprofessional.

**Comment by ehofesmann** [comment]
Hi @sp01186, questions like these are best answered in our Slack community: https://join.slack.com/t/fiftyone-users/shared_invite/zt-s6936w7b-2R5eVPJoUw008wP7miJmPQ, but it's perfectly fine to ask them here as well. 

To answer your question, you can achieve what you are trying to do by using the [export](https://voxel51.com/docs/fiftyone/user_guide/export_datasets.html#cocodetectiondataset) method on the FiftyOne dataset that you have already loaded in Python. Note, you cannot export classifications in COCO format, so just the detections that you loaded.
```python
dataset = foz.load_zoo_dataset(
    "open-images-v6",
    split="train",
    label_types=["detections", "classifications"],
    classes=["Airplane","Cat", "Dog"],
    max_samples=2500,
)

# You fill this in
export_dir = "/path/to/coco-dataset"

dataset_or_view.export(
    export_dir=export_dir,
    dataset_type=fo.types.COCODetectionDataset,
    label_field="detections",
)
```

The convert method you are using will take datasets directly from disk, but the must be exactly in the format you specify, and since the open images dataset is not in `FiftyOneImageDetectionDataset` format, it is not converted properly.

There is no way to delete an issue permanently, but you can close it if your issue is resolved.
