### ISSUE TITLE
[?] How to best load custom formatted data into FiftyOne

### ISSUE THREAD

**Issue by VLDMR-BS** [voxel51/fiftyone#2020]
Hi! You have a pretty cool tool that helps you work with data and thank you for the opportunity to use it.

I also have suggestions for improving this tool to make it even more convenient and cool to use. I work for a company that has made its own dataset format, thus we do not have the opportunity to use your tool. However, in addition to my company, there are also many different dataset formats that also cannot interact with your tool. I would like to correct this moment and make some changes in your code, however, I came across the fact that there are 2 ways, one of which I like more, but entails much more changes in the code base, the other is simpler and easier to implement, but it will work slower.

The first option, which is simple, is to make a code for distilling datasets from one format to another and, at startup, specify which dataset format to work with now, and then the dataset will be distilled from its original format to COCO format, however, this is very resource-intensive and will work slower + disk space is needed to implement this format distillation

The second option is to make a dataset class that will act as an API to the data and apply a factory that will pull up the necessary dataset class and provide all the necessary data, respectively, then support for the new format will be conditioned only by another class and work with your tool will not be slowed down, since the dataset will be read without transformations. However, this will require more code changes.

Thank you for your attention, and I will wait for your answer, because I want not just to implement the functionality, but to give all users the opportunity to use it, since these changes, in my opinion, will be useful and expand the use of your cool tool.

**Comment by brimoor** [comment]
Hi @VLDMR-BS 👋  glad you like the project and want to help improve it for both you and others!

Building an API to pull data dynamically from another source into FiftyOne would be very difficult, because pretty much all of FiftyOne's features, such as querying for samples through the App or in code ([dataset views](https://voxel51.com/docs/fiftyone/user_guide/using_views.html)), require the dataset's metadata to be available in FiftyOne's standard format in MongoDB.

Therefore, my recommendation would be to pursue your option 1: write an importer that can translate your dataset format into FiftyOne's format. This will involve pulling the metadata into MongoDB, but, importantly, it does not require modifying or moving the actual media files on disk.

Here's our documentation on all the formats that FiftyOne natively supports importing from (eg COCO):
https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#supported-import-formats

For loading custom formatted data into FiftyOne, there are two basic options:
- Write a simple Python function that does the conversion: https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/index.html#custom-formats
- Write a customer dataset importer that formalizes the above function into a reusable component: https://voxel51.com/docs/fiftyone/user_guide/dataset_creation/datasets.html#custom-formats
