### ISSUE TITLE
[FR] Have Mapbox token configuration error link to token generation docs

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#2169]
The error that is raised whenever a mapbox token is not provided but attempting to visualize a geolocation map in the App should have a link directly to this page to let the user know how to configure a token: https://docs.mapbox.com/help/getting-started/access-tokens/

**Comment by swheaton** [comment]
Wouldn't this be better off to point to: https://voxel51.com/docs/fiftyone/user_guide/app.html#map-tab ?
Because that section contains a link to the mapbox doc above _plus_ how to actually set the token so that it will be used.
Otherwise the user will just be sent to make a mapbox token but not know what to do with it.

**Comment by brimoor** [comment]
@swheaton I agree 👍
