### ISSUE TITLE
[DOCS] YOLOv5DatasetExporter label conversion undocumented

### ISSUE THREAD

**Issue by ztyree42** [voxel51/fiftyone#2322]
`YOLOv5DatasetExporter` calls `_make_yolo_row` under the hood and documentation says nothing about this. A user that is familiar with YOLO style annotations and needs to convert a different annotation format to YOLO will probably (definitely?) convert their bounding boxes to normalized (xc, yc, w, h) before exporting which will yield incorrect bboxes since `_make_yolo_row` is already doing this and assumes it's receiving normalized (xtl, ytl, w, h). Probably this call should just be removed since presumably users would like to export the bboxes they have defined themselves but short of that at least it should be documented that bboxes should be formatted in this rather non-standard way.

**Comment by brimoor** [comment]
The `YOLOv5DatasetExporter` is implemented the way that it is because FiftyOne expects that all `Detection.bounding_box` labels that you add to your FiftyOne datasets are stored in this format:

```
[<top-left-x>, <top-left-y>, <width>, <height>]
```

https://voxel51.com/docs/fiftyone/user_guide/using_datasets.html#object-detection

It sounds like you are storing bounding boxes in different formats in your FiftyOne dataset, which I would not recommend because it would mean that the FiftyOne App (for example, but also other parts of the library) will not be able to visualize your boxes correctly.

**Comment by ztyree42** [comment]
Right, I get that the exporter is doing the conversion under the hood but
if you're not aware of that and do the conversion manually it's a bit of a
footgun. Just my 2 cents being new to fiftyone but not data annotation
generally.
