### ISSUE TITLE
[BUG] Fiftyone Logging

### ISSUE THREAD

**Issue by nsriniva03** [voxel51/fiftyone#2456]
Hello,

If I set fo.config.logging_level = logging.CRITICAL, FiftyOne still outputs log of type INFO. How can you ignore outputting log message of type info to stdout? I was specifically trying to not output _APP_NOTEBOOK_MESSAGE = """
Session launched. Run `session.show()` to open the App in a cell output.
"""

Thank you

**Comment by brimoor** [comment]
Hi @nsriniva03 👋 

I believe your issue is that, unlike some `fo.config` settings, updating `fo.config.logging_level` in an existing session will not automatically change the logging level, as logging is initialized only when `fiftyone` is first imported.

You can customize logging level via environment variable prior to importing `fiftyone`:

```shell
export FIFTYONE_LOGGING_LEVEL=ERROR
```

You can customize logging level after import by calling `fiftyone.set_logging_level()` directly:

```py
import logging
import fiftyone as fo

logger = logging.getLogger("fiftyone")
logger.info("This is logged")

fo.set_logging_level(logging.ERROR)
logger.warning("This is not logged")
```

Or you can manually trigger logging to be reconfigured by calling `fiftyone.core.logging.init_logging()`:

```py
import fiftyone.core.logging as fol

fo.config.logging_level = "CRITICAL"
fol.init_logging()

logger.error("This is also not logged")
```
