### ISSUE TITLE
[FR][Willing to contribute] Is there features to check weather a dataset has loaded annotations or not, and to check weather a dataset's annotation is exported or not?

### ISSUE THREAD

**Issue by stevezkw1998** [voxel51/fiftyone#2756]
### Instructions

We know to load annotations, using
```python
dataset.load_annotations(anno_key)
```
Is there any API that can check whether this dataset has already loaded any annotation or not? like
```python
dataset.has_loaded_annotations()
# return True or False
```

We know to export an annotation/label, using
```python
        dataset.export(
            export_dir=export_dir,
            dataset_type=dataset_type,
            export_media=False
        )
```
Is there any API that can check whether this dataset has already loaded any annotation or not? like
```python
dataset.has_been_exported()
# return True or False
```

### Proposal Summary

These features can help avoid repeated operations and make fiftyone easier to be used and easier to be secondary developed.

### Motivation

-   What is the use case for this feature? 
When we want datasets to be only annotated and exported once.
-   Why is this use case valuable to support for FiftyOne users in general?
This use case reduces conflicts in multi-user collaborating-labeling.
-   Why is this use case valuable to support for your project(s) or organization?
This use case reduces conflicts in multi-user collaborating-labeling.
-   Why is it currently difficult to achieve this use case?
Currently, the best method to achieve I found is:
 ```python
results = dataset.load_annotation_results(anno_key)
s = results.to_str()
import json
json_dict = json.loads(s)
```
And check whether the field `'id_map'`  has other key besides `'None': {}`
Which is too much trouble to implement.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here.

### Willingness to contribute

The FiftyOne Community welcomes contributions! Would you or another member of your organization be willing to contribute an implementation of this feature?

-   [x] Yes. I can contribute this feature independently
-   [ ] Yes. I would be willing to contribute this feature with guidance from the FiftyOne community
-   [ ] No. I cannot contribute this feature at this time

**Comment by swheaton** [comment]
For 1: This will be tough because what if you delete the annotation run, then you cannot rely on it to tell you if annotations have been loaded. If you know the field name for annotations then you can check for existence of the field in the field schema.
We could add a single-use flag to the dataset saying whether it's been exported, but I think this is nonstandard and not generally useful. You could always add this custom field to your datasets as part of your workflow and set this field to True when exported, or tag the dataset.
 
For 2: No there would be no way to know this since you could have exported it anywhere. Also, same answer as above, use custom field or tags in your workflow.
