### ISSUE TITLE
[DOCS] reencode_video and original movies

### ISSUE THREAD

**Issue by allenleetc** [voxel51/fiftyone#2909]
### URL(s) with the issue
https://docs.voxel51.com/api/fiftyone.utils.video.html?highlight=reencode_videos#fiftyone.utils.video.reencode_videos

### Description of proposal (what needs changing)
Current doc suggests that `reencode_videos` will reencode current videos in-place. Actual behavior appears to be, dataset filepaths are unchanged, but original video is backed up to <name>_original.mp4. This seems goodish but not indicated in doc. See also `delete_originals` kwarg

**Comment by timmermansjoy** [comment]
To clarify the OSS slack comment:

1. reencode video to `_reencoded.mp4`
2. delete og file
3. rename reencoded file
4. (optional) if keyboard interrupt is called (SIGTERM), delete `_reencoded.mp4` file to not have lingering corrupt files.

this way you will not get missing files in your fiftyone database because the path has changed of the original file. now you are GOING TO HAVE issues, when you stop a `reencode` run. not that its possible, you are going to have issues because your file has changed from the start.

my proposal makes that likelihood in comparison non existent because the only time this can happen is when the file got deleted and the other file didn't get renamed, a process that takes nanoseconds vs minutes while reencoding. 

alternatively you could start changing the file in fiftyone to the `_original.mp4` in the time being that its reencoding but then you are making a lot of calls to different things that can go wrong like the rename didn't go trough in the mongodb.

Also in fiftyone teams, you can have multiple people working on a dataset, 1 could be reencoding a file and then in that time it becomes corrupt for other users in that period since the file path is not correct, while the proposed method also makes it possible to have people still access the file while its being reencoded
