### ISSUE TITLE
[FR] FiftyOne Support for Multi-Label Classifications with Label Studio Integration

### ISSUE THREAD

**Issue by lkaneda** [voxel51/fiftyone#2946]
### Proposal Summary

**_Help us improve the Label Studio integration!_** 

With the Label Studio integration in FiftyOne, add support for multi-label classification by adding support for the Classifications label type.

### Motivation

Label Studio supports multi-label classifications on their platform. While FiftyOne can support multi-label classification through the Classifications type, the Label Studio integration does not currently support it. Adding this would provide a richer integration experience between FiftyOne and Label Studio.

### What areas of FiftyOne does this feature affect?

-   [ ] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [ ] Server: FiftyOne server

### Details

Currently, the Label Studio integration supports the [Classification](https://docs.voxel51.com/api/fiftyone.core.labels.html#fiftyone.core.labels.Classification) type. In order to support multi-label classifications, the integration will need to support the [Classifications](https://docs.voxel51.com/api/fiftyone.core.labels.html#fiftyone.core.labels.Classifications) type.

You can learn more about the Label Studio integration in FiftyOne [here](https://docs.voxel51.com/integrations/labelstudio.html#label-studio-integration).

### Looking for Help

FiftyOne is an app centered around our community. To continuously improve the open source solution, we're searching for contributors to help improve (and contribute new!) features. This is one of those that we hope to get community support on. If you'd like to help us out, feel free to pick this up and ask us questions here or [in the slack community](https://fiftyone-users.slack.com/join/shared_invite/zt-s6936w7b-2R5eVPJoUw008wP7miJmPQ#/shared-invite/email)!

In exchange for your help, you'll get some pretty sweet FiftyOne swag!

**Comment by tataganesh** [comment]
Hey @lkaneda,
Are you still looking for contributors for this issue?

**Comment by brimoor** [comment]
Hi @tataganesh 👋 

Yes, a contribution for this would be amazing!

**Comment by tataganesh** [comment]
Great, thanks @brimoor ! Would you have any pointers to get started with the support for the `Classifications` type?

**Comment by brimoor** [comment]
@tataganesh absolutely!
1. The labelstudio integration is implemented here: https://github.com/voxel51/fiftyone/blob/develop/fiftyone/utils/labelstudio.py
2. Documentation for using the integration: https://docs.voxel51.com/integrations/labelstudio.html
3. Documentation for multilabel classifications: https://docs.voxel51.com/user_guide/using_datasets.html#multilabel-classification

**Comment by tataganesh** [comment]
Thank for the clarification questions! I had a follow-up question (sorry if I am misunderstanding something) - 

I am going through labelstudio.py and I noticed that in the `export_label_to_label_studio` function, both `Classification` and `Classifications` types are checked: 

https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/fiftyone/utils/labelstudio.py#L710

Looking at the `_to_classification` function:

https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/fiftyone/utils/labelstudio.py#L763-L768

Could you clarify if this means some support for exporting multi-label classifications already exists?

**Comment by brimoor** [comment]
Hmm that's interesting, looks like there indeed may already be some partial support.

Upon a brief glance, it looks like there's at least a couple other changes needed:

1. Add `"classifications"` here to formally declare support for `Classifications`-type labels: 
https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/fiftyone/utils/labelstudio.py#L99-L115

2. Update this line:
https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/fiftyone/utils/labelstudio.py#L894
to return a `Classifications` label rather than a raw list:
```py
    return fol.Classifications(
        classifications=[fol.Classification(label=l) for l in label_values]
    )
```

3. Update the docs (documenting for myself; I can handle this part 😄):
 - https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/docs/source/integrations/labelstudio.rst?plain=1#L29
- https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/docs/source/integrations/labelstudio.rst?plain=1#L418

Ultimately the way to test that everything is working as expected is to run the [basic recipe](https://docs.voxel51.com/integrations/labelstudio.html#basic-recipe) on a dataset that contains some `Classifications` labels and checking that everything works as expected.

**Comment by tataganesh** [comment]
This is great @brimoor, thank you for the breakdown! I will try to submit a PR soon!

**Comment by tataganesh** [comment]
@brimoor 
I have started working on this issue and I am unable to resolve an error. I have made the changes mentioned in your comment, and when I try to test it I get an error on this line:

https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/fiftyone/utils/labelstudio.py#L419

Error:
```
    results[sample_id] = {l.id: (ln, l) for (ln, l) in labels}
AttributeError: 'Classifications' object has no attribute 'id'
```

I noticed that the `Classifications` object has no `id` attribute (only the `Classification` object does). So I made the following change to the `import_label_studio_annotation` function. 

Changes made to lines:
https://github.com/voxel51/fiftyone/blob/c6c4abbaae570dec14f3855ccb0a007ecf18f250/fiftyone/utils/labelstudio.py#L677

Changed lines:
```python
        if isinstance(label, fol.Classifications):
            for l in label.classifications:
                l.id = label_id
        else:
            label.id = label_id
```

And changed

```
 results[sample_id] = {l.id: (ln, l) for (ln, l) in labels} 
```
to 

```python
results[sample_id] = {}
for ln, l in labels:
    if isinstance(l, fol.Classifications):
        label_id = l.classifications[0].id
        results[sample_id][label_id] = (ln, l)
    else:
        results[sample_id][l.id] = (ln, l)
```
But even if with this I get some other error. Any help would be appreciated to resolve this error, thank you!

**Comment by brimoor** [comment]
@tataganesh looping in @ehofesmann who can help advise on how to proceed here (when he has some bandwidth!)

**Comment by ehofesmann** [comment]
Hey @tataganesh! I believe the issue is that for a label list like Classifications, the `results` object is expecting the label of each classification to be unique. So when you do this:
```python
        if isinstance(label, fol.Classifications):
            for l in label.classifications:
                l.id = label_id
```
Then all of the individual fo.Classification labels have the same ID which would cause issues downstream, likely the error that you're seeing. I believe the `final_annotations` dictionary from `download_annotations` would then have a structure like this `{label_field: {return_type: {sample_id: {label_id: fo.Classification}}}}`. Notably that the end label id would correspond to a single fo.Classification, of which there could be multiple for a single sample
