### ISSUE TITLE
[BUG] custom colors are not saving properly

### ISSUE THREAD

**Issue by manivoxel51** [voxel51/fiftyone#3335]
Applying custom color to labels do not show in the UI - I can confirm they show in the DB under app_config. The following is the [example in our doc](https://docs.voxel51.com/api/fiftyone.core.odm.dataset.html#fiftyone.core.odm.dataset.ColorScheme)

```
import fiftyone as fo
import fiftyone.zoo as foz

dataset = foz.load_zoo_dataset("quickstart")

dataset.app_config.color_scheme = fo.ColorScheme(
   color_pool=["#ff0000", "#00ff00", "#0000ff", "pink", "yellowgreen"],
   fields=[
     {
             "path": "ground_truth",
             "fieldColor": "#ff00ff",
             "colorByAttribute": "label",
             "valueColors": [{"value": "dog", "color": "yellow"}],
         }
     ]
)
dataset.save()
session = fo.launch_app(dataset)
```

The dataset document in the db has an updated app config but UI is not showing

**Comment by lanzhenw** [comment]
I am closing this ticket, because it is working. 

At the moment, the app's default setting is to color by field, so all ground_truth annotations will use "#ff00ff" as the color. 
If the user wants to see dogs as yellow, they need to open the color modal and toggle `color by` to `value`. 

In the next release, all settings on `global settings page` in color modal will persist, and user can specify the desired color by mode in the code directly.
