### ISSUE TITLE
[BUG] Out-of-memory in from_dir() when importing segmentation data

### ISSUE THREAD

**Issue by cipri-tom** [voxel51/fiftyone#3438]
### System information

-   **OS Platform and Distribution** (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
-   **Python version** (`python --version`): Python 3.9.16
-   **FiftyOne version** (`fiftyone --version`): FiftyOne v0.21.6, Voxel51, Inc.
-   **FiftyOne installed from** (pip or source): pip

### Commands to reproduce

```python
isaid_root = Path('/home/data/iSAID/')
ds_name = 'val'
dataset = fo.Dataset.from_dir(
    name="iSAID-seg-val",
    overwrite=True,
    dataset_type=fo.types.COCODetectionDataset, 
    data_path=isaid_root / ds_name / 'images', 
    labels_path=isaid_root / ds_name / 'Annotations' / f'iSAID_{ds_name}.json',
    label_types=['segmentations'],
    num_workers=10,    # reported as not used 
)

```

### Describe the problem

I am trying to import the [**iSAID**](https://captain-whu.github.io/iSAID/dataset.html) image segmentation dataset. It consists of images from [DOTA v1.5](https://captain-whu.github.io/DOTA/dataset.html), plus the annotation files on iSAID website.

I'm starting with the validation dataset, as it contains only 458 images. However, these images have 116649 annotations. When loading the dataset as shown above (`from_dir()`), the program runs out of memory and gets killed by the system. I have 58 Gb of RAM available on this box.

### Code to reproduce issue

See above, it is really simple, just calling `from_dir()` with the right directory. If you'd like some code to download the dataset, it is tough to produce as the dataset is downloaded from the author's Google Drive, which is difficult to script (wget does not work). But I can indicate which files to get.

### Other info/logs

In order to understand the problem, I ran a debugger on the code. It seems the problem is coming from `_coco_objects_to_detections()`:

https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/utils/coco.py#L2046-L2067

I stopped the debugger there, and used [Pympler](https://pympler.readthedocs.io/en/latest/#usage-examples) to assess the memory usage of objects:

(in the debugger window)
```python
from pympler import asizeof

asizeof.asizeof(detection)
# 11726016 - bytes, one detection

asizeof.asizeof(detection) // 2**20
# 11 - MB, one detection

asizeof.asizeof(detections) // 2**20
# 23947 - MB, all detections so far, 2142 of them

asizeof.asizeof(detections) // 2**30
# 23 - GB
```

[Screenshot of VSCode with debugger and above code](https://github.com/voxel51/fiftyone/assets/2991890/a535795f-48ec-48bc-ad20-557bd4e68062)

This is in accordance to what I see in `htop` memory usage (my highlight in red)

![screenshot of htop utility showing about 28 Gb of memory usage for this python process](https://github.com/voxel51/fiftyone/assets/2991890/6154d055-e02e-4785-bb1f-ccb1e55dfda6)

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core Python library issue
-   [ ] `Server`: FiftyOne server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another member of your organization be willing to contribute a fix for this bug to the FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently
-   [x] Yes. I would be willing to contribute a fix for this bug with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a bug fix at this time

At this point, I'm not sure what the fix could be. It seems a big change is needed in order to commit each detection to the database, rather than build the whole list in memory.

**Comment by brimoor** [comment]
By default, FiftyOne's COCO importer represents each instance segmentation as a bounding box together with a boolean numpy array whose pixel count is proportional to the box's area wrt the entire image. Here's the COCO mask conversion code:
https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/utils/coco.py#L2154

The `_coco_objects_to_detections()` function assumes that it can fit all instance segmentations for one image in memory, but it seems like this dataset contains one image with at least 2142 instance segmentations? Which takes >23GB to represent in FiftyOne's `Detections` format.

`from_dir()` processes all the images using `map()`:
https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/utils/data/importers.py#L140-L146

which should be smart enough to garbage collect between samples, since the COCO importer only calls 
`_coco_objects_to_detections()` on one image at a time:
https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/utils/coco.py#L427

So the number of images in the dataset should not matter; only the max size of one image's annotations.

Even if you had enough RAM to store the `Detections` for this 2142 instance image in-memory, FiftyOne has a 16MB limit for each `Sample` object stored in the database. So the `Detections` label type wouldn't work for this dataset.

**Comment by brimoor** [comment]
Perhaps you can try passing [`use_polylines=True`](https://github.com/voxel51/fiftyone/blob/71714f20aef5490e978b026e2c2dc4dfeec707c0/fiftyone/utils/coco.py#L324-L326)?

```py
dataset = fo.Dataset.from_dir(
    ...,
    dataset_type=fo.types.COCODetectionDataset,
    use_polylines=True,
    ...,
)
```

This will store the instance segmentations as polylines (lists of vertex coordinates) instead. Perhaps in this representation each sample will be <= 16MB?

**Comment by cipri-tom** [comment]
Thank you for the quick response and detailed explanation ! 

Indeed, that image had more than 2100 objects. And I later realised it was another image that was crashing the kernel. One that is 6635 x 6508 px, and has more than 3000 objects. I had stopped the kernel just before eating all the 60 Gb of RAM, and it had only processed 1272 out of 3200 objects, for a total of 53 Gb of memory.

But yes, I am glad to report that `use_polylines=True` has solved the problem. I imported the whole dataset, and it never used more than 3 GB or RAM. 

Thanks a lot!
