### ISSUE TITLE
[DOCS] Loading COCO object detection automatically converts bounding box format to normalised COCO.

### ISSUE THREAD

**Issue by WHBSmith** [voxel51/fiftyone#3510]
### URL(s) with the issue

https://docs.voxel51.com/user_guide/dataset_creation/index.html
https://docs.voxel51.com/user_guide/export_datasets.html#cocodetectiondataset
https://docs.voxel51.com/integrations/coco.html#:~:text=Loading%20the%20COCO%20dataset&text=FiftyOne%20supports%20loading%20annotations%20for,(see%20below%20for%20details).

### Description of proposal (what needs changing)

It is wild that the only place I could find that tells you the bounding box format for an imported COCO dataset is automatically converted to normalised COCO is in a note halfway down (https://docs.voxel51.com/user_guide/using_datasets.html) and there is no documentation or inbuilt function for converting it back. The COCO integration page shows a standard COCO annotation and doesn't even mention this issue which is so misleading. Importing a COCO dataset is one of the most basic tasks so it is really disappointing to find how badly documented this is. 

Also how does this work for models taken outside of fiftyone, does this mean training a model with samples from a fiftyone dataset will lead to raw detections output in the fiftyone format? If the model is taken elsewhere does this mean that the output needs to be converted from fiftyone format back to COCO?

As a side note the example in https://docs.voxel51.com/user_guide/dataset_creation/index.html#model-predictions doesn't run successfully on my version of fiftyone (0.21.6) and returns an error 'Dataset has no field'ground_truth'.

### Willingness to contribute

The FiftyOne Community encourages documentation contributions. Would you or another member of your organization be willing to contribute a fix for this documentation issue to the FiftyOne codebase?

-   [ ] Yes. I can contribute a documentation fix independently
-   [x] Yes. I would be willing to contribute a documentation fix with guidance from the FiftyOne community
-   [ ] No. I cannot contribute a documentation fix at this time

**Comment by brimoor** [comment]
Hi William, as you pointed out [on this page](https://docs.voxel51.com/user_guide/using_datasets.html#object-detection), FiftyOne stores all object detections in this specific format:

> FiftyOne stores box coordinates as floats in [0, 1] relative to the dimensions of the image.
> Bounding boxes are represented by a length-4 list in the format:
> 
> `[<top-left-x>, <top-left-y>, <width>, <height>]`

Note that this is not "normalized COCO" per se, but rather FiftyOne's standard format (which wouldn't change if the normalized COCO spec were to change, for example).

It is necessary for FiftyOne datasets to store data in a common format so that the App knows how to correctly visualize them. Storing the data in a single standard format also allows for the reverse workflow: exporting data into any one of the builtin formats (COCO, YOLO, VOC, etc):
https://docs.voxel51.com/user_guide/export_datasets.html

As for training models, here's a couple useful tutorials:
- Training with Detectron2: https://docs.voxel51.com/tutorials/detectron2.html
- Adding classifier predictions from a model to FiftyOne: https://docs.voxel51.com/recipes/adding_classifications.html
- Adding detections predictions from a model to FiftyOne: https://docs.voxel51.com/recipes/adding_detections.html
- Training a model using a FiftyOne dataset:

**Comment by brimoor** [comment]
Thanks for catching the documentation bug for COCO on  https://docs.voxel51.com/user_guide/dataset_creation/index.html#model-predictions. The correct syntax for the function call beginning on line 24 of the example code is:

```py
# Now load ground truth labels into a new dataset
dataset2 = fo.Dataset.from_dir(
    dataset_dir="/tmp/coco",
    dataset_type=fo.types.COCODetectionDataset,
    label_field="ground_truth",
    label_types="detections",
)
```

This has been patched and the updated docs will be deployed to fiftyone.ai in a few days.
