### ISSUE TITLE
Evaluating predictions

### ISSUE THREAD

**Issue by nasserdr** [voxel51/fiftyone#3719]
I would appreciate if someone can help me in this issue. As I am newbie in fiftyone, I am not really sure where the starting point is for evaluating models (after I have computed the predictions).

I have a dataset created as follows:
`    dataset = fo.Dataset('my_dataset')
    
    dataset.add_dir(
        data_path = "./data/training/image_2",
        labels_path = "./data/training/label_2",
        dataset_type=fo.types.KITTIDetectionDataset,
        split='trainval',
        tags='trainval'
    )
    
    dataset.add_dir(
        data_path = f"./data/testing/image_2",
        labels_path = f"./data/testing/label_2",
        dataset_type=fo.types.KITTIDetectionDataset,
        split='test',
        tags='test'
    )
    dataset.persistent = True
`

I am able to visualize it with fiftyone app and also play around with the interface. I have 4 models and I have their predictions on the testing set. The predictions are in Kitti format.

I am looking for starting point or recipes for these issues:
- Adding predictions to the dataset: Is it possible to add 4 predictions to the same model and still be able to visualize all of the them in the app with different colors?
- Is it possible to visualize both the grounf truth and the predictions in the same time?
- How can I compute the commonly know evaluation metrics? Is that possible only using a python code or can I use the app for that? NB. I want to be able to compute the evaluation metrics without running model predictions again (as I already have the predictions dumped in Kitti format).

Thanks a lot.

**Comment by swheaton** [comment]
Hi @nasserdr welcome to the FiftyOne community then! Feel free to join our [community slack](https://slack.voxel51.com) where you can get help from others, feature updates, give feedback, and more.

As to your specific q's:

- Yes you can add any custom metadata fields you want, including predictions. Many people add a new detection field, e.g., to the same dataset for each model training run, in order to compare and evaluate models. You could add the new fields by adding detections directly [this way](https://docs.voxel51.com/user_guide/dataset_creation/index.html#model-predictions), or potentially using [`merge_dir()`](https://docs.voxel51.com/api/fiftyone.core.dataset.html#fiftyone.core.dataset.Dataset.merge_dir) which works similary to the `add_dir()` method you've already used.
- Yep absolutely, this is bread and butter FiftyOne app. Check out [using the app user guide](https://docs.voxel51.com/user_guide/app.html#using-the-sidebar) to see how the labels fields can be toggled on and off, filtered, colored differently, and more.
- See the [evaluating models user guide](https://docs.voxel51.com/user_guide/evaluation.html#) for more. This is with python code yes, but you could also install the [evaluation plugin](https://github.com/voxel51/fiftyone-plugins/tree/main/plugins/evaluation) and then do it all through the app!

**Comment by nasserdr** [comment]
Hello @swheaton,

Thanks for your input.

I was able to add the predictions of several models to several dataset. That works super fine and it's indeed a life saving feature. This allowed me to make some visual inspections. Now, I am moving to concretize my results with numbers, but I ran into troubles.

Visually speaking, my results seem to be appealing, where I can see the predicted bounding boxes mostly aligned with the annotations.

However, computing the metrics seem to bear wrong results. Here's a snapshot.
![image](https://github.com/voxel51/fiftyone/assets/15745564/7376d99a-b66c-4b31-af59-dbb5ef0ec139)

I am sure that the results should not be zero but I am not able to find the glitch. Also, I it seems that the performance is measured on the whole dataset (~2900 images). How can I make it measure the mAP on the test set only?

![image](https://github.com/voxel51/fiftyone/assets/15745564/eb7172dc-61fc-4a20-84e9-b32035c3103c)


Thanks

**Comment by swheaton** [comment]
The boxes are hard to see, I recommend a [custom color scheme](https://docs.voxel51.com/user_guide/using_datasets.html#custom-color-scheme).

Just from my naked eye, I don't see any overlapping boxes in this view but again it's hard to tell because of the colors.

To your second question, you could run `evaluate_detections()` on a view containing only 'test' tag.
```python
view = dataset.match_tags("test")
view.evaluate_detections ( ... )
```

**Comment by nasserdr** [comment]
Thanks, I actually had another glicht completely unrelated to the evaluations, that's why I was getting a zero, but not only. Evaluating metrics on the whole dataset seems to be uncorrect. The metrics on the test view are different that on the whole dataset:

On the test view (79 samples):
`              precision    recall  f1-score   support

       rumex       0.62      0.31      0.42       343

   micro avg       0.62      0.31      0.42       343
   macro avg       0.62      0.31      0.42       343
weighted avg       0.62      0.31      0.42       343
`
On the dataset (794 samples):
`              precision    recall  f1-score   support

       rumex       0.62      0.05      0.09      2162

   micro avg       0.62      0.05      0.09      2162
   macro avg       0.62      0.05      0.09      2162
weighted avg       0.62      0.05      0.09      2162
`
I would say that this is expected because the valtrain set does not contains any predictions but only ground truth.
