### ISSUE TITLE
Default github branch should be master

### ISSUE THREAD

**Issue by tylerganter** [voxel51/fiftyone#378]
I think we should update the repo to have `master` as the default branch, not `develop`

**Comment by brimoor** [comment]
I agree, but first we need to establish a convention (automatically @lethosor?) of merging tagged releases into `master`. I just updated `master`, but that was the first time in months we've updated it.

Any discussion on this?

**Comment by tylerganter** [comment]
Yep I agree with your point as well. Not sure how important it is that automatic merging is established first, but this is not high priority IMO anyway.

**Comment by lethosor** [comment]
My main concern with doing this is that people landing on the repo homepage won't see the latest changes and might not know where to find them. If we do this, we'll need to make it clear (e.g. in the readme) that active development takes place on another branch. This is admittedly less of a concern if releases are more frequent.

Is your goal here to guide people towards more stable code by default? There's an argument to be made for using the released builds instead. Running from source is mostly useful for development, and developers should generally be basing their work on `develop` instead of `master` - in some cases, starting on `master` could result in duplicating work that has already been done on `develop`.

I don't see a particularly strong need to automate merging into master, since other parts of the release process are manual anyway. I would like to make sure that protection rules are set up to avoid the need to make a pull request for every merge into master, though (like ccdc4ad9f03d00276ed46159ad1c157812a15f96).
