### ISSUE TITLE
What is difference?

### ISSUE THREAD

**Issue by devgod1007** [voxel51/fiftyone#4591]
What's the difference between fiftyone.brain.similarity.find_unique() and fiftyone.brain.compute_uniqueness()? 
The output of both the functions using the same embeddings are slightly different.

**Comment by swheaton** [comment]
The difference is slightly subtle.
[`compute_uniqueness()` ](https://docs.voxel51.com/api/fiftyone.brain.html#fiftyone.brain.compute_uniqueness) adds a uniqueness score to each sample representing how unique it is with respect to the rest of the samples. Taking the top N would give you the N samples that are most unique compared to the entirety of the dataset.

[`find_unique()`](https://docs.voxel51.com/api/fiftyone.brain.similarity.html#fiftyone.brain.similarity.DuplicatesMixin.find_unique) selects `count` samples that are maximally unique _with respect to each other_. 

To explain with help of a degenerate case ... let's say we have 1000 images of dogs and 2 duplicate images of a tree. Those 2 tree images are probably going to have very high uniqueness scores because they're very different than the 1000 dog images. But if we call `find_unique()` then you would not expect to get the 2 tree images as a result because they are not unique with respect to _each other_.
