### ISSUE TITLE
[BUG] Windows tests failing due to pip permission issues

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#510]
https://github.com/voxel51/fiftyone/runs/1086721641

Error 1:

```
Run pip install --upgrade pip setuptools wheel
Collecting pip
  Downloading pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
Collecting setuptools
  Downloading setuptools-50.3.0-py3-none-any.whl (785 kB)
Collecting wheel
  Downloading wheel-0.35.1-py2.py3-none-any.whl (33 kB)
Installing collected packages: pip, setuptools, wheel
  Attempting uninstall: pip
    Found existing installation: pip 20.2.2
    Uninstalling pip-20.2.2:
      Successfully uninstalled pip-20.2.2
ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-uninstall-od1eiz3s\\pip.exe'
Consider using the `--user` option or check the permissions.

##[error]Process completed with exit code 1.
```

Error 2:

```
Run find tests/isolated/ -name '*.py' -print0 | xargs -0 --verbose -n1 python tests/utils/pytest_wrapper.py --verbose
python tests/utils/pytest_wrapper.py --verbose tests/isolated/import_deps_test.py 
Traceback (most recent call last):
  File "tests/utils/pytest_wrapper.py", line 7, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
python tests/utils/pytest_wrapper.py --verbose tests/isolated/import_time_test.py 
Traceback (most recent call last):
  File "tests/utils/pytest_wrapper.py", line 7, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
python tests/utils/pytest_wrapper.py --verbose tests/isolated/server_tests.py 
Traceback (most recent call last):
  File "tests/utils/pytest_wrapper.py", line 7, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
python tests/utils/pytest_wrapper.py --verbose tests/isolated/service_tests.py 
Traceback (most recent call last):
  File "tests/utils/pytest_wrapper.py", line 7, in <module>
    import psutil
ModuleNotFoundError: No module named 'psutil'
##[error]Process completed with exit code 123.
```

**Comment by lethosor** [comment]
The second error is expected/irrelevant; those tests always run, and are failing because the required packages could not be installed. Specifically:
* " Install fiftyone dependencies" was skipped because upgrading pip failed
* " Run isolated tests" always runs, so that it runs even if "Run tests" fails: https://github.com/voxel51/fiftyone/blob/2d0c4306627c7873155ede7b4b08c3fceec2a335/.github/workflows/build.yml#L103
  * This failed because fiftyone's dependencies were not installed

This may be something that changed in GitHub's runner environment over the weekend, since it was working previously: https://github.com/voxel51/fiftyone/runs/1069857481?check_suite_focus=true
There are a couple other ways to upgrade pip that I'll try to resolve this.

**Comment by lethosor** [comment]
I think the issue here is that [pip 20.2.3](https://pypi.org/project/pip/20.2.3/) was released around 5 hours ago, and `setup-python` is still using 20.2.2, so upgrading pip is actually doing something now (which fails on Windows), while it was previously a no-op. 73915877 seems to have helped, anyway.
