### ISSUE TITLE
[FR] Hide App scroll bars when not scrolling

### ISSUE THREAD

**Issue by brimoor** [voxel51/fiftyone#546]
The scroll bar in image grid mode is now always visible, whereas previously it would only appear when scrolling (on Mac).

Scroll bar behavior/look-and-feel is somewhat OS dependent, but the convention on the web is to hide scroll bars when not scrolling for Mac users. I think we should provide the same behavior for users of our App. (IE revert to previous behavior from earlier App versions)

**Comment by lethosor** [comment]
To clarify: the scroll bars are actually only visible when your cursor is over a scrollable area, and are hidden otherwise. 0.5.3-0.5.4 *always* hid scrollbars on all OSes, and releases before that relied on the system default, which was inconsistent with the rest of the app on Linux/Windows. The current behavior is a middle ground between entirely-unthemed scrollbars and your desired behavior.

Improving the scrollbar experience is definitely on our radar. A couple major obstacles to this currently:
* Native scrollbars (which we are styling) do not support CSS transitions, so we can't make them fade in and out
* There does not appear to be a way to show them only when their container is actually being scrolled (and in any case, I don't think that we want this, because visible scrollbars are currently the primary indicator that a container can be scrolled)

**Comment by benjaminpkane** [comment]
Yes, I was happy with the change because it will force us to come to a long term solution faster. So we can then forget about it and move on.

I could write a few paragraphs about this, but @lethosor hit the key points.

**Comment by benjaminpkane** [comment]
I'm working on this. I just would like to make scrollbars look decent on other Linux and Windows and not have them mess up layouts so much.
