### ISSUE TITLE
[BUG] Model zoo requirements should not have to be pip installed

### ISSUE THREAD

**Issue by ehofesmann** [voxel51/fiftyone#734]
When ensuring the requirements of a model in the zoo, packages like TensorFlow could have been installed from source or through conda and should be usable even if not installed through `pip`.

**Comment by brimoor** [comment]
Figuring out what non-pip thing a user used to install a package is probably a black hole. That's why I added an `error_level` parameter to all the relevant zoo model methods that allows you to suppress error messages that don't apply to you.

There's a note to this effect on the [zoo homepage](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/index.html), and it is explained in more detail in [places like this](https://voxel51.com/docs/fiftyone/user_guide/model_zoo/api.html#loading-zoo-models).

LMK if the docs aren't clear or you have other thoughts on how to better address this.

**Comment by ehofesmann** [comment]
Ah, right, that should work. I missed that though so I think I'll make a PR to make it a little more clear in the docs what the individual error levels represent.

**Comment by ehofesmann** [comment]
Also there should be some way to do this through the CLI without having to change the global parameter.

**Comment by brimoor** [comment]
https://github.com/voxel51/fiftyone/pull/735.

**Comment by ehofesmann** [comment]
Clarified error levels in https://github.com/voxel51/fiftyone/pull/739
