### ISSUE TITLE
[FR] Add support for URL-based samples

### ISSUE THREAD

**Issue by benjaminpkane** [voxel51/fiftyone#768]
### Proposal Summary

Proposing URLs are supported as a  sample's `filepath`. Or, perhaps a mutually exclusive reserved field, `url`, is added. Furthermore, it would be ideal if datasets could support a mixture of `filepath` and `url` samples.

### Motivation

Adding support for URL-backed samples, as opposed disk-backed samples, would increase the flexibility and agility of creating FiftyOne datasets.

### What areas of FiftyOne does this feature affect?

-   [x] App: FiftyOne application
-   [x] Core: Core `fiftyone` Python library
-   [x] Server: FiftyOne server

**Comment by brimoor** [comment]
I think I like generalizing the existing `filepath` field to allow for URLs.

The reason is that providing both `filepath` and `url` would suggest that we are moving in a direction where you could have multiple sources of data for a given dataset (e.g., first load from `filepath` if it is available, else fallback to `url`). This could be an interesting direction to go in the future, but just not sure we want to go there just yet.

But, I'm certainly open to other opinions on this.

**Comment by benjaminpkane** [comment]
We could change `filepath` to something like `source` need be.

**Comment by benjaminpkane** [comment]
Being worked on for [FiftyOne Teams](https://voxel51.com/#teams-form). Includes cloud storage support.

**Comment by xiao2mo** [comment]
Hi has this problem been fixed now?  Maybe an inevitable property for visualization.

**Comment by benjaminpkane** [comment]
Hi @xiao2mo. URLs are supported in [FiftyOne](https://voxel51.com/#teams-form). Feel free to reach out!

**Comment by xiao2mo** [comment]
> 

Thanks bro!

**Comment by tadejsv** [comment]
@benjaminpkane Is this supported in the open source version, or only in Teams?

**Comment by swheaton** [comment]
@tadejsv this is currently a Teams feature. In OSS you can use [cloud storage](https://docs.voxel51.com/faq/index.html#can-i-access-data-stored-in-the-cloud) by mounting the cloud bucket as a filesystem. I'm not sure of a workaround for URL paths though.
