### ISSUE TITLE
[BUG] "Show no confidence" does not seem to work properly in Colab

### ISSUE THREAD

**Issue by kylemin** [voxel51/fiftyone#789]
### System information

-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Colab (quickstart.ipynb)
-   **FiftyOne installed from (pip or source)**: !pip install fiftyone (in Colab)
-   **FiftyOne version (run `fiftyone --version`)**: 0.7.1.4?
-   **Python version**: 3.6.9

### Commands to reproduce

In "quickstart.ipynb", I double-clicked the one of the validation images. In the LABELS tab, there are two "Show no confidence" options each for the ground-truth and the predictions. Both options do not work properly.

### Describe the problem

If I click off the "Show no confidence" of the ground-truth, all the ground-truth bounding boxes disappear. If I click off the button of the predictions, nothing happens.

### Code to reproduce issue

Please follow the "quickstart.ipynb" in Colab.

### Other info / logs

N/A

### What areas of FiftyOne does this bug affect?

-   [x] `App`: FiftyOne application issue
-   [ ] `Core`: Core `fiftyone` Python library issue
-   [ ] `Server`: Fiftyone server issue

### Willingness to contribute

The FiftyOne Community encourages bug fix contributions. Would you or another
member of your organization be willing to contribute a fix for this bug to the
FiftyOne codebase?

-   [ ] Yes. I can contribute a fix for this bug independently.
-   [ ] Yes. I would be willing to contribute a fix for this bug with guidance
        from the FiftyOne community.
-   [x] No. I cannot contribute a bug fix at this time.

**Comment by benjaminpkane** [comment]
Hi @kylemin! It is expected that unchecking "Show no confidence" for the `ground_truth` field will hide all `ground_truth` detections because no ground truth detections have a confidence value. And, for the `predictions` field, all detections have a confidence value, so unchecking "Show no confidence" for `predictions` will not hide any  of its detections.

Perhaps you could describe what you are expecting from these actions?

Thanks for trying out the quickstart!

**Comment by kylemin** [comment]
Well, I think that unchecking the "Show no confidence" for predictions should hide their confidence values. But currently, nothing happens. In addition, the "Show no confidence" for the ground-truth may not be necessary? I think it is unintuitive. All the ground-truth detections have no confidence, then why do we have the option?

**Comment by benjaminpkane** [comment]
I see your point. The checkbox should probably be renamed to something like `Filter no confidence` because it is a filtering operation. Filtering does conflict with the fact the the top-level field checkboxes only toggle labels. We will have to think about this.

I will note that there is a "Show confidence" option within the image viewer itself. It will apply to all label fields, though.
![Screenshot from 2021-01-18 11-31-29](https://user-images.githubusercontent.com/19821840/104952192-42205300-5981-11eb-807f-4826b8ff0b91.png)

**Comment by kylemin** [comment]
Oh, I see. Thank you!
